SET IDENTITY_INSERT [dbo].[Banks] ON
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (1, N'State Bank of India')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (2, N'ICICI Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (3, N'Bandhan Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (4, N'Punjab National Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (5, N'Bank of Baroda')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (6, N'Axis Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (7, N'HDFC Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (8, N'Andhara Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (9, N'Citi Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (10, N'Dena Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (11, N'JP Morgan Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (12, N'Yes Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (13, N'BankOfIndia')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (14, N'IDBI Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (15, N'Vijiya Bank')
INSERT INTO [dbo].[Banks] ([BankId], [BankName]) VALUES (16, N'Kotak Mahindra Bank')
SET IDENTITY_INSERT [dbo].[Banks] OFF
