SET IDENTITY_INSERT [dbo].[LedgerTypes] ON
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (1, N'Salary', 3, N'For Employees')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (2, N'Telephone & Internet', 3, N'Telephone bill')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (3, N'Lunch & Snacks', 3, N'Lunch & Snacks')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (4, N'Tailoring Trims', 3, NULL)
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (5, N'Ads', 3, NULL)
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (6, N'Store Maintenance & Repair', 3, NULL)
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (7, N'Suspense  Expenses', 3, NULL)
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (8, N'Electricity', 3, N'Electricity')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (9, N'Postage', 3, N'Postage')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (10, N'HomeExpenses', 3, N'HomeExpenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (11, N'Out of Store', 3, N'Out of Store')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (12, N'Assests', 3, N'Assests')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (13, N'Freight', 3, N'Freight')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (14, N'Serivces', 3, N'Serivces')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (15, N'Tax & Duties', 3, N'Tax & Duties')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (16, N'Workshop', 3, N'Workshop expenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (17, N'Tailoring Trims', 3, N'Tailoring Trims Purchase')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (18, N'No Party', 3, N'No Party')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (19, N'Car Maintance', 3, NULL)
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (20, N'Puja Expenses', 3, N'puja expenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (21, N'Decoration Expenses', 3, N'Decoration Expenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (22, N'Computer & IT', 4, N'Computer & IT')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (23, N'Painting goods', 3, N'Painting goods')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (24, N'Wallpaper Mistry', 3, N'Wallpaper Mistry')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (25, N'Printing goods', 3, N'Stationary')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (26, N'Municipal Tax & rent ', 3, N'Tax & others')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (27, N'M.S Benaguria', 2, N'M.S Benaguria')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (28, N'Veena Press', 3, N'Veena Press')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (29, N'Home Electricity Bill', 3, N'Electricity')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (30, N'Shop Electricity Bill', 3, N'Electricity')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (31, N'Workshop Electricity bill', 3, N' Electricity')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (32, N'Stationary', 3, N'Stationary')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (33, N'Furniture of Aprajita Retails', 3, N'Furniture of Aprajita Retails')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (34, N'Electricity Account', 0, N'Electricity Account')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (35, N'Point Redenative', 3, N'Point Redenative')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (36, N'Net Communication', 3, N'Net Communication')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (37, N'Travelling & Trip Expenses ', 0, N'Travelling & Trip Expenses ')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (38, N'Dan', 3, N'Dan')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (39, N'Anubha Kumari', 3, N'Anubha Kumari')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (40, N'Iron elements', 3, N'Iron elements')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (41, N'Electronics Goods', 3, N'Electronics Goods')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (42, N'FirstFloorOffice', 3, N'First Floor Office Expenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (43, N'R.S Furniture', 3, N'R.S Furniture')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (44, N'Staff Shoes', 3, N'Staff Shoes')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (45, N'Arvind Groups', 9, N'Arvind Limited Groups')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (46, N'EDC & Bank Charges', 3, N'Bank Charges Expenses')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (47, N'Vena', 3, N'Verna(Fuel Expenses)')
INSERT INTO [dbo].[LedgerTypes] ([LedgerTypeId], [LedgerNameType], [Category], [Remark]) VALUES (48, N'Tiles Mistri', 3, N'Tiles Mistri')
SET IDENTITY_INSERT [dbo].[LedgerTypes] OFF
