INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ADR', N'Arvind Ready Wear')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'AGV', N'Arvind GV')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ANK', N'Ankur Fabrics')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARA', N'Arvind Accessories')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARD', N'Arvind')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARI', N'Arvind')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARN', N'Arrow New York')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARP', N'Arvind Promo')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARR', N'Arrow')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARS', N'Arrow Sports')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ARV', N'Arvind Store')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'ASW', N'Arvind Swatch')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'FM', N'Flying Machine')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'HAN', N'Hanes International')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'IZ', N'Izod')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'NAT', N'Nautica')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'SAR', N'Studio Arvind')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'SAT', N'Studio Arvind Tailored')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'THF', N'Tommy Hilfiger')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'UD', N'US DENIM & Co')
INSERT INTO [dbo].[VoyBrandNames] ([BRANDCODE], [BRANDNAME]) VALUES (N'USP', N'US Polo Association')
