SET IDENTITY_INSERT [dbo].[BankWithdrawals] ON
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (1, N'2019-12-01 07:49:01', 9, N'', N'Bandhan_CurrentAcc', CAST(15000.0000 AS Money), 1, N'ATM WITHDRAWAL', N'Amit Kumar', N'Amit Kumar', N'testing', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (2, N'2020-01-10 07:54:17', 2, N'', N'ICICI_Sav_2791', CAST(15000.0000 AS Money), 6, N'MUKESH MANDAL', N'Amit Kumar', N'Alok Kumar', N'002104', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (3, N'2020-01-24 07:58:28', 2, N'', N'ICICI_Sav_2791', CAST(20000.0000 AS Money), 6, N'MUKESH MANDAL', N'Amit Kumar', N'Alok Kumar', N'002106', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (4, N'2020-07-31 08:01:24', 9, N'', N'Bandhan_CurrentAcc', CAST(70000.0000 AS Money), 6, N'SELF', N'Alok Kumar', N'Alok Kumar', N'211', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (5, N'2020-08-21 08:03:48', 2, N'', N'ICICI_Sav_2791', CAST(72000.0000 AS Money), 0, N'Alok for Bhakat Brothers', N'Alok Kumar', N'Alok Kumar', N'ATM withdrawl', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (6, N'2020-08-21 08:03:48', 2, N'', N'ICICI_Sav_2791', CAST(20000.0000 AS Money), 0, N'Alok for ANUP SHARMA', N'Alok Kumar', N'Alok Kumar', N'ATM withdrawl', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (7, N'2020-08-26 08:07:32', 2, N'', N'ICICI_Sav_2791', CAST(10000.0000 AS Money), 0, N'Alok Kumar', N'Alok Kumar', N'Alok Kumar', N'ATM WITHDRAWL', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (8, N'2020-09-25 02:37:32', 2, N'', N'ICICI_Sav_2791', CAST(10000.0000 AS Money), 0, N'FOR CASH', N'Alok Kumar', N'Alok Kumar', N'ATM WITHDRAWL', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (9, N'2020-09-30 08:13:29', 6, N'', N'AprajitaRetails_ICICI', CAST(700000.0000 AS Money), 0, N'SELF', N'Amit Kumar', N'Amit Kumar', N'ch.num:-002179', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (10, N'2020-11-13 08:18:40', 3, N'', N'ATM CASH ', CAST(10000.0000 AS Money), 1, N'FOR CASH', N'Alok Kumar', N'Alok Kumar', N'ATM WITHDRAWL', 1)
INSERT INTO [dbo].[BankWithdrawals] ([BankWithdrawalId], [OnDate], [BankAccountId], [ChequeNo], [InNameOf], [Amount], [PayMode], [Details], [SignedBy], [ApprovedBy], [Remarks], [StoreId]) VALUES (12, N'2021-06-02 08:20:36', 6, N'', N'AprajitaRetails_ICICI', CAST(35000.0000 AS Money), 0, N'self for cash', N'Amit Kumar', N'Alok Kumar', N'22148', 1)
SET IDENTITY_INSERT [dbo].[BankWithdrawals] OFF
