INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7491', N'Apparel/Tailored Garment/Shirts')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7511', N'Apparel/Tailored Garment/Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7512', N'Apparel/Tailored Garment/Suits')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7513', N'Apparel/Tailored Garment/Jackets')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7533', N'Apparel/Tailored Garment/Jeans')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7551', N'Apparel/Tailored Garment/JawaharJacket')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7552', N'Apparel/Tailored Garment/Sherwani')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7553', N'Apparel/Tailored Garment/Overcoat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7554', N'Apparel/Tailored Garment/Waist Coat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7555', N'Apparel/Tailored Garment/Jodhpuri')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7562', N'Apparel/Tailored Garment/Pathani Suit')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7563', N'Apparel/Tailored Garment/Safari Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7564', N'Apparel/Tailored Garment/Safari Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7565', N'Apparel/Tailored Garment/Kurta')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7566', N'Apparel/Tailored Garment/Pyjama')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7567', N'Apparel/Tailored Garment/Breeches')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7568', N'Apparel/Tailored Garment/DhotiPatiala')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7569', N'Apparel/Tailored Garment/Pathani Top')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7570', N'Apparel/Tailored Garment/Salwar')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7571', N'Apparel/Tailored Garment/Tie')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7572', N'Apparel/Tailored Garment/Scarf')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7573', N'Apparel/Tailored Garment/Apron')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7574', N'Apparel/Tailored Garment/Night Dress')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7671', N'Apparel\Accessories\Lug - Backpack')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7691', N'Apparel\Accessories\TIES-HANKY-LIC')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7733', N'Apparel/Mens Formal/Vest Coat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7751', N'Apparel/Accessories/Acc- Boxer')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7774', N'Creyate/Mens/Blazer')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7776', N'Creyate/Mens/Chinos')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7777', N'Creyate/Mens/Jeans')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7778', N'Creyate/Mens/VestCoat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7779', N'Creyate/Mens/Suits')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7780', N'Creyate/Mens/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7791', N'Creyate/Mens/Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7792', N'Creyate/Mens/Sleeve')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7793', N'Creyate/Mens/WaistCoat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7813', N'Creyate/Mens Formal/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7815', N'Creyate/Mens Casual/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7816', N'Creyate/Womens/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7817', N'Creyate/Womens/Jeans')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7820', N'Creyate/Womens Formal/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7821', N'Creyate/Womens Casual/Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7853', N'Suiting/Tresca/Wool Silk')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7871', N'Shirting/Tresca/Poly Cot')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7892', N'Promo/Accessory/Style Duffle')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7916', N'Broches/Arv Accessories/Accessories')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'7971', N'Suiting/Tresca/Poly Cot')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8034', N'Suiting/Denim/Poly Cot')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8035', N'Suiting/Tresca/Cot Modal')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8036', N'Shirting/Tresca/Cot Modal')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8038', N'Suiting/Denim/Poly Visc')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8054', N'Apparel/Work/Polos')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8056', N'Apparel/Work/Blazers')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8057', N'Apparel/Work/Shirts')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8058', N'Apparel/Work/Suits')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8059', N'Apparel/Work/Trousers')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8060', N'Apparel/Work/Waistcoat')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8063', N'Apparel/After Hours/Bundis')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8064', N'Apparel/After Hours/Suits')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8065', N'Apparel/After Hours/Blazers')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8067', N'Apparel/After Hours/Jeans')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8068', N'Apparel/After Hours/Knit bottoms')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8069', N'Apparel/After Hours/Kurtas')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8070', N'Apparel/After Hours/Polo')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8071', N'Apparel/After Hours/Shirts')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8072', N'Apparel/After Hours/Shorts')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8073', N'Apparel/After Hours/Tee')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8074', N'Apparel/After Hours/Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8077', N'Apparel/Celebration/Bandhgala')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8078', N'Apparel/Celebration/Bespoke day jacket')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8079', N'Apparel/Celebration/Bundis')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8080', N'Apparel/Celebration/Dinner jackets')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8081', N'Apparel/Celebration/Achkan')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8082', N'Apparel/Celebration/Kurtas')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8083', N'Apparel/Celebration/Shirts')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8084', N'Apparel/Celebration/Trousers')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8085', N'Churidar/Celebration/Apparel')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8200', N'Suit Cover/Arv Accessories/Accessories')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8220', N'Apparel/Celebration/Suits')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8240', N'Apparel/Mens Casual/Trackpants')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8260', N'Shirting/Tresca/Cotton Visc Visc')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8280', N'Promo/Accessory/Gold Coin')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8321', N'Shirting/Tresca/Cotton Ten')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8360', N'Shirting/Non Tresca/Cotton Ten')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8380', N'Shirting/Tresca/Poly Visc')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8400', N'Apparel/Accessories/Gift Set')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8401', N'Apparel/Accessories/Bow-Tie')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8420', N'Poly/Tresca/Shirting')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8422', N'Poly/Non Tresca/Shirting')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8423', N'Suiting/Tresca/Poly')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8424', N'Suiting/Non Tresca/Poly')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8440', N'Apparel/Accessories/Acc. - Cufflinks')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8441', N'Apparel/Accessories/Combo set')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8520', N'Apparel/Mens Western/TC Bandi')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8540', N'Apparel/Mens Western/TC Blazer')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8560', N'Apparel/Mens Western/TC Knitted Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8561', N'Apparel/Mens Western/TC Polo T Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8580', N'Apparel/Mens Western/TC TShirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8581', N'Apparel/Mens Western/TC Woven Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8582', N'Apparel/Mens Western/Tc Woven Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8583', N'Apparel/Mens Ethenic/TB-SharwaniWoven')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8584', N'Apparel/Mens Ethenic/TB-Kurtas Set')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8585', N'Apparel/Mens Western/TJ Polo T Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8600', N'Apparel/Mens Western/TJ TShirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8601', N'Apparel/Mens Western/TJ Woven Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8602', N'Apparel/Mens Western/TJ Woen Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8603', N'Apparel/Mens Western/TI Bandi')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8620', N'Apparel/Mens Western/TI Blazer')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8621', N'Apparel/Mens Western/TI Knitted Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8622', N'Apparel/Mens Western/TI Polo Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8623', N'Apparel/Mens Western/TI Suit')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8624', N'Apparel/Mens Western/TI Woven Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8625', N'Apparel/Mens Western/TI Woven Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8626', N'Apparel/Mens Western/TU Bandi')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8627', N'Apparel/Mens Western/TU BLAZER')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8628', N'Apparel/Mens Western/TU Jacket')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8629', N'Apparel/Mens Western/TU Jeans')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8630', N'Apparel/Mens Western/TU Knitted Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8631', N'Apparel/Mens Western/TU Pol TShirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8632', N'Apparel/Mens Western/TU Sweat Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8633', N'Apparel/Mens Western/TU Sweater')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8634', N'Apparel/Mens Western/TU TShirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8635', N'Apparel/Mens Western/TU Woven Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8636', N'Apparel/Mens Western/TU Woven Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8640', N'Apparel/Mens Ethenic/TB-IndoWesternwo')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8641', N'Apparel/Accessories/Bow')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8642', N'Apparel/Accessories/Hanger')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8660', N'Apparel/Mens Western/TU SHORTS')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8662', N'Apparel/Non Apparels/TU Carry Bag')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8663', N'Apparel/Non Apparels/TU Hanger')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8664', N'Apparel/Non Apparels/TU BELT LEATHER')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8665', N'Apparel/Non Apparels/TU Belt Nonleath')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8666', N'Apparel/Mens Ethenic/TB BANDI WOVEN')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8667', N'Apparel/Mens Ethenic/TB WOVEN Trouser')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8680', N'Apparel/Mens Western/TB T-SHIRT')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8700', N'Apparel/Mens Western/TB Shirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8723', N'Suiting/Primante/POLY WOOL')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8741', N'Suiting/Primante/ALL WOOL')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8760', N'Suiting/Primante/Wool Silk')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8780', N'Apparel/Mens Western/TI Tshirt')
INSERT INTO [dbo].[ProductMasters] ([PRODUCTCODE], [PRODUCTNAME]) VALUES (N'8801', N'PPE Kit/Arv Accessories/Accessories')
