SET IDENTITY_INSERT [dbo].[Contacts] ON
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (1, N'AJAM', N'MASTER', N'9973599123', NULL, NULL, N'Tailor Master')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (2, N'Rajshree ', N'Himopt', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (3, N'Raju ', N'Dangal', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (4, N'Rajuji Jitendar', N'Gupta', N'993-404-0524', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (5, N'Rakesh ', N'Electrician', N'948-021-2596', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (6, N'Rakesh singhania', N'Dumka', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (7, N'Ram Avatar Uncle ', N'', N'94313 10434', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (8, N'Ramanad Radha Guest', N'House', N'969-344-0845', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (9, N'Ramchandar ', N'Seo', N'917352369758', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (10, N'Rames ', N'Gup', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (11, N'Ramprasad Chennai', N'Transacar', N'7299011991', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (12, N'RajKumar 6th', N'Gear', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (13, N'Randheer Maa', N'Guest', N'773-911-2939', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (14, N'Ranjeet ', N'New', N'917070643567', N'', N'kirankumar.p@hdfs.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (15, N'Ranjeet ', N'Sis', N'706-309-3243', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (16, N'Ranjeet New', N'Latest', N'8757461991', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (17, N'Ranu Singh', N'Madhupur', N'919934379373', N'', N'sumit.agarwal@franchiseindia.in', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (18, N'Ranu Singh ', N'Carmel', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (19, N'Ratan ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (20, N'Ravi ', N'Icici', N'+91 95990 86208', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (21, N'Ravi Sony', N'Eletronic', N'977-147-7735', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (22, N'Ravindra Arvind', N'Store', N'919899977505', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (23, N'Ravindra Ele', N'mistry', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (24, N'Ranjedra ', N'Gupta', N'+91 96613 42107', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (25, N'Ritesh Nair Arvind', N'Limited', N'+91 99091 05838', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (26, N'Rajiv Narayan ', N'Gupta', N'+91 98312 32945', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (27, N'Rajesh Modi Marble Shop ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (28, N'Piles ', N'Free', N'093-100-06356', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (29, N'Pink ', N'Thailand', N'+66 84 215 7595', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (30, N'Pinku ', N'Pareshar', N'+91 94313 84852', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (31, N'Pk ', N'Dutta', N'919431160287', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (32, N'PNB Durgapur  ', N'', N'+91 70444 81471', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (33, N'Police ', N'', N'100', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (34, N'Pradeep Sbi', N'Lic', N'776-503-3717', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (35, N'Pradeep Title Jai Mata', N'Di', N'919973472046', N'', N'help@uidai.gov.in', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (36, N'Prakash charan', N'Yadav', N'919771492807', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (37, N'Pratik ', N'Arvind', N'918335855210', N'9123333273', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (38, N'Rajiv ', N'Ranjan', N'943-119-4093', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (39, N'Prince Broker ', N'', N'93046 98511', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (40, N'Raj Kishore. Kk Shastry', N'Friend', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (41, N'Raj Nandi ', N'Hdfc Bm', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (42, N'Rajak Ass.', N'Eng', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (43, N'Rajeev ', N'Mahindra', N'773-912-5555', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (44, N'Rajeev ', N'Spiada', N'84095 46069', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (45, N'Rajesh ', N'Hyderbad', N'984-906-7052', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (46, N'Rajesh  Tax Consultant', N'Blr', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (47, N'Rajesh Andand', N'Dto', N'923-435-2668', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (48, N'Rajesh Kumar', N'Chacha', N'099-990-07088', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (49, N'Rajesh Kumar', N'Chourasia', N'919431156010', N'', N'campco9431156010@gmail.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (50, N'Pritam Block Dumka  ', N'', N'87893 16177', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (51, N'Pick ', N'It', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (52, N'Rockey Jio', N'Dumka', N'917004439107', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (53, N'S Mishra ', N'', N'+91 70910 73434', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (54, N'Sapan ', N'Das', N'954-677-5306', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (55, N'Sarvesh Anand', N'America', N'17048318865', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (56, N'Sashi ', N'Singh', N'+91 62999 28328', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (57, N'Sashi Kant', N'Siwan', N'+91 99814 14101', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (58, N'Sasidhar ', N'Manda', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (59, N'Shiv Tas', N'J', N'7004478715', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (60, N'Somnath Tas', N'J', N'7908829165', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (61, N'Staff Santosh ', N'', N'+91 99348 20819', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (62, N'Sujit Chota', N'Thakur', N'918084679474', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (63, N'Sujit Thakur ', N'', N'+91 89867 02276', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (64, N'Santosh Singh', N'Gridhid', N'94314 38827', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (65, N'Sukhen ', N'', N'+91 98310 67082', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (66, N'Sunil Pipe Mistry ', N'', N'88735 23295', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (67, N'Sunil Tiwari ', N'', N'919831213336', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (68, N'Suresh ', N'Paswan', N'943-115-8207', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (69, N'Tailor ', N'From Mdp', N'919431165043', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (70, N'Tailor Zafar', N'Patna', N'918434450309', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (71, N'Tarak Hyduni', N'Dgp', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (72, N'Tarun ', N'', N'995-538-3382', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (73, N'Tarun Arvind IT', N'team', N'982-440-5430', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (74, N'Taufik Jamin', N'Dumka', N'+91 99555 27930', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (75, N'TCI express gridhi ', N'', N'917739139200', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (76, N'Sunil Master', N'Dumka', N'900-681-1951', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (77, N's ', N'panjlkar', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (78, N'Santosh Ji ', N'Deoghar', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (79, N'Santosh ', N'Gridhi', N'917004842327', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (80, N'Sachin ', N'Suhasaria', N'990-305-7085', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (81, N'Sachin Charan', N'Mishra', N'917979916899', N'', N'sachinmishra.munnababu1985@gmail.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (82, N'Saikat Airbnb', N'Kol', N'+91 98300 74596', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (83, N'Sajeev Mishra Staff', N'Ar', N'918936876694', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (84, N'Saksh ', N'', N'919379127572', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (85, N'Sambhu ', N'deo', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (86, N'Samir ', N'Kumar Milkman', N'+91 79034 58233', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (87, N'Samir Goria', N'Da', N'77630 99800', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (88, N'Samrat Siromani', N'Tecnocrat', N'919304119550', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (89, N'Sanaul ', N'Mistry', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (90, N'Santosh ', N'Raymond', N'919122398536', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (91, N'Sanjay ', N'Jagdis', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (92, N'Sanjay Modi', N'Sareeniketan', N'919431945152', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (93, N'Sanjay Ranchi  ', N'Sheshank Person', N'+91 82103 62180', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (94, N'Sanjeev ', N'Jaiswal', N'+91 80022 77120', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (95, N'Sanjeev Kumar', N'Patna', N'080-025-93227', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (96, N'Sanjeev Mariqueen', N'Delhi', N'919810037560', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (97, N'Sanjeev Mishra', N'staff', N'918271599052', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (98, N'sanjeev zuari', N'furniture', N'094-313-68410', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (99, N'Sanjiv Mishra Staff', N'Ok', N'917903665080', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (100, N'Sanju ', N'Nurse', N'095-055-35366', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (101, N'Sanoj ', N'ICICI home loan', N'977-143-0731', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (102, N'Sanjay Kumar', N'Bhalotia', N'+91 70042 49395', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (103, N'Phralad ', N'Sah', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (104, N'Persent ', N'Rajm', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (105, N'Pawan ', N'Sighania', N'098-310-29399', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (106, N'Dtdc ', N'dumka', N'993-408-0075', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (107, N'Dumka icici branch manager ', N'Mehria', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (108, N'Ebiz ', N'', N'+91 73590 29994', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (109, N'Emergency ', N'Care', N'1-057-11', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (110, N'Fasttag ', N'Jamshedpur', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (111, N'Fire ', N'', N'101', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (112, N'Ganesh ', N'Lp', N'996-408-0106', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (113, N'Ganesh ', N'Pune', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (114, N'Gaurav ', N'Sharma', N'919748537865', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (115, N'Gautam Ril', N'Fin', N'918709547563', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (116, N'Dr john ', N'Mukherjee', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (117, N'Gautam Security Guard Mainaak ', N'', N'+91 97480 86956', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (118, N'Ghar ka', N'khana', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (119, N'Glub C', N'Bhagat', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (120, N'GM Dumka Industry', N'Dept', N'916434236209', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (121, N'Gopal ', N'Vaia', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (122, N'Gopal Nath ', N'', N'919431395797', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (123, N'Gopal Twiari Shaibgang ', N'', N'62016 25554', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (124, N'gopal yadav son in law pc', N'yadav', N'886-289-5000', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (125, N'GOPI', N'CHOURASIA', N'9934080104', N'9334247706', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (126, N'Harinandan ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (127, N'Himalaya Optical Kolkata  ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (128, N'Ghansyam ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (129, N'Illys Nakum Arvind  ', N'', N'095101 01067', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (130, N'Door Computers Pvt', N'Ltd', N'9434014491', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (131, N'Dinesh Bhaiya Bgp', N'Road', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (132, N'ALOK', N'KUMAR', N'9386601284', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (133, N'Amit', N'Kumar', N'09831213339', N'7779997556', N'amitnarayansah@gmail.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (134, N'Amit Bandhan', N'Bank', N'+91 87099 52812', N'          ', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (135, N'Anil Jha', N'Landlord Aryan Comp', N'8877097815', N'', N'', N'land lord of aryan computer building')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (136, N'Ankush Rajhajan ', N'', N'72177 07848', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (137, N'Arinban ', N'', N'+91 79798 10766', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (138, N'Attamram ', N'', N'9470105175', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (139, N'Augustin ', N'Harly', N'+91 90070 67429', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (140, N'Automecha ', N'Manjot', N'+91 98307 91911', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (141, N'Avinash ', N'Azad', N'+91 98209 53719', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (142, N'Divyanshu Block Dumka  Broker ', N'', N'88252 80104', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (143, N'Avinash Singh ', N'', N'+91 94313 67599', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (144, N'B ', N'Patwari', N'89866 71806', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (145, N'B Rai ', N'', N'92042 04090', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (146, N'B Shridhar ', N'', N'998-633-1585', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (147, N'Bablu ', N'Phatak', N'9431185292', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (148, N'Badari Rai Adv ', N'', N'+91 92042 04690', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (149, N'Basant Phariya', N'Koriya', N'919934142847', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (150, N'Basant Rolick ', N'', N'+91 78705 46505', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (151, N'C A Bikas', N'Patwari', N'763-113-9955', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (152, N'Dilip ', N'Sharma', N'919431310413', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (153, N'Dinesh ', N'Mamaji', N'+91 98309 16617', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (154, N'Aziz Ji', N'Arvind', N'+91 97237 09902', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (155, N'Indu ', N'Gupta', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (156, N'Indu Bhushan Singh', N'Singh', N'+91 96611 20021', N'', N'indu07bhushan@gmail.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (157, N'Jamshedpur Cc Camera ', N'', N'+91 94313 29838', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (158, N'KITES', N'AQ UA', N'9931843289', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (159, N'Kk Pal  ', N'Spl', N'83350978897', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (160, N'Kulkarni ', N'Bmw Navnit Motors', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (161, N'Lala ', N'Bhai', N'887-651-5412', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (162, N'Lalan ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (163, N'Laloo Dumka', N'Swankar', N'918409239766', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (164, N'Land Near Parmondi Hasda ', N'', N'+91 84093 88384', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (165, N'Latest ', N'Scheme', N'1213', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (166, N'Laxman ', N'new', N'+91 77590 84408', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (167, N'LAYMANS', N'BRODBAND', N'7908201267', N'7484065443', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (168, N'Kishor ', N'Phralad', N'919701387741', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (169, N'Manj ', N'Pande', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (170, N'Mukesh ', N'Pansari', N'988-327-0932', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (171, N'Mukesh Hyundai Showroom', N'Kol', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (172, N'Nishant Singh', N'Deoghar', N'090-978-17388', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (173, N'Nishant Singh Deoghar ', N'Jio', N'+91 94709 99900', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (174, N'P ', N'Chowbey', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (175, N'P ', N'Kitkit', N'084-345-25187', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (176, N'Pankaj ', N'Arvind', N'918697973887', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (177, N'Pankaj ', N'Verma', N'+91 79038 34240', N'', N'pankaj68099@gmail.com', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (178, N'Pankaj Sharma Maharaja', N'Sweet', N'99559 13380', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (179, N'Pappu ', N'Gurao', N'099-532-99143', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (180, N'Manmeet ', N'HimOpt Deoghar ', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (181, N'Kishan  ', N'Kumar', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (182, N'Kaveri Fishing', N'Camp', N'082-124-44444', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (183, N'Kaushal ', N'Mamma', N'728-300-0327', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (184, N'Jauari ', N'Furniture', N'957-010-0187', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (185, N'JAYKRISHNA', N'ICICI', N'932125473', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (186, N'Jayprakas ', N'Jrmd', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (187, N'Jayprakash Kitkit', N'Mama', N'993-970-4989', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (188, N'Jaywardhan ', N'Ready', N'900-092-9320', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (189, N'Jharsurguda TAS ', N'Orissa', N'919861440155', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (190, N'Jio ', N'Gopi', N'99340 80104', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (191, N'Jio-Complaint ', N'Helpline', N'198', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (192, N'Jio-General ', N'Helpline', N'199', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (193, N'Jio-Tele-verification ', N'Helpline', N'1977', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (194, N'Jitedar Deo', N'S', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (195, N'Jitendar ', N'Gupta', N'954-664-0411', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (196, N'Jitendr ', N'Dhanba', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (197, N'Jithendra ', N'Bn', N'', N'', N'', N'Name: Belur & Co,  ac no 34970804222, State Bank of India, girinagar branch, IFSC: SBIN0016222')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (198, N'Jonshon Titles  ', N'Dumka ', N'072-928-21824', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (199, N'Joy ', N'Chakarborty', N'993-436-0837', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (200, N'Joydeep ', N'Advace Power', N'919163673609', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (201, N'Jyoti ', N'Adv', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (202, N'Kalyan Adv ', N'', N'977-170-5939', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (203, N'Kamalkanta ', N'Shastry', N'+91 98008 32500', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (204, N'Kamalkanta Office ', N'', N'', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (205, N'Karan ', N'Agarwal', N'983-006-9112', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (206, N'Karunesh Ji', N'Arvind', N'90739 29595', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (207, N'Tirpuari Balav Nirmal Kr Jha  ', N'', N'+91 80843 66632', N'', N'', N'')
INSERT INTO [dbo].[Contacts] ([ContactId], [FirstName], [LastName], [MobileNo], [PhoneNo], [EMailAddress], [Remarks]) VALUES (208, N'Udit Narayan ', N'Sah', N'+91 99551 04272', N'', N'', N'')
SET IDENTITY_INSERT [dbo].[Contacts] OFF
