SET IDENTITY_INSERT [dbo].[CashReceipts] ON
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (1, N'2020-12-22 00:00:00', 6, N'sushil kumar jhunjhunwala', CAST(1000000.0000 AS Money), N'ardr0046', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (2, N'2020-12-12 00:00:00', 6, N'pankaj verma', CAST(99000.0000 AS Money), N'', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (3, N'2020-10-06 00:00:00', 6, N'GOPI CHOUASIA', CAST(110000.0000 AS Money), N'ARDR0030', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (4, N'2020-10-02 00:00:00', 6, N'colour mistry for Bamboo', CAST(150.0000 AS Money), N'', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (5, N'2020-09-09 00:00:00', 6, N'AMIT JEE(OLD LOAN OF MUKESH MANDAL)', CAST(5000.0000 AS Money), N'', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (6, N'2020-08-22 00:00:00', 7, N'ELECTRIC MISTRY(PAMENT DT:-21.08.2020', CAST(100.0000 AS Money), N'', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (7, N'2020-07-20 00:00:00', 6, N'amit jee', CAST(5000.0000 AS Money), N'withdrowl from atm', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (8, N'2020-07-19 00:00:00', 6, N'amit kumar(on line transfer a/c of alok kumar)', CAST(5000.0000 AS Money), N'', N'Imported', N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[CashReceipts] ([CashReceiptId], [InwardDate], [TranscationModeId], [ReceiptFrom], [Amount], [SlipNo], [Remarks], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (9, N'2020-07-11 00:00:00', 6, N'amit jee', CAST(10000.0000 AS Money), N'received through atm withdrowl', N'Imported', N'AmitKumar', 0, 1, 1)
SET IDENTITY_INSERT [dbo].[CashReceipts] OFF
