SET IDENTITY_INSERT [dbo].[Brands] ON
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (1, N'Arvind Ready Wear', N'ADR')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (2, N'Tommy Hilfiger', N'THF')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (3, N'Studio Arvind Tailored', N'SAT')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (4, N'Studio Arvind', N'SAR')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (5, N'Nautica', N'NAT')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (6, N'Izod', N'IZ')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (7, N'Hanes International', N'HAN')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (8, N'Flying Machine', N'FM')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (9, N'Arvind Swatch', N'ASW')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (10, N'US DENIM & Co', N'UD')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (11, N'Arvind Store', N'ARV')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (12, N'Arrow', N'ARR')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (13, N'Arvind Promo', N'ARP')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (14, N'Arrow New York', N'ARN')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (15, N'Arvind', N'ARI')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (16, N'Arvind', N'ARD')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (17, N'Arvind Accessories', N'ARA')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (18, N'Ankur Fabrics', N'ANK')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (19, N'Arvind GV', N'AGV')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (20, N'Arrow Sports', N'ARS')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (21, N'US Polo Association', N'USP')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName], [BCode]) VALUES (22, N'No Brand', N'NBR')
SET IDENTITY_INSERT [dbo].[Brands] OFF
