SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (1, N'Shirting', 1, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (2, N'Sweater', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (3, N'Sweat Shirt', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (4, N'Accessories', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (5, N'After Hours', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (6, N'Trouser', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (7, N'Work', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (8, N'Celebration', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (9, N'Suits', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (10, N'Blazers', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (11, N'Bundis', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (12, N'Suit Cover', 1, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (13, N'Arv Accessories', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (14, N'Wool Silk', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (15, N'Cotton Visc Visc', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (16, N'WirstWatch', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (17, N'Blazer', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (18, N'Style Duffle', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (19, N'Bag', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (20, N'Innerwear', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (21, N'Briefs', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (22, N'Vests', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (23, N'Jackets', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (24, N'Acc- Boxer', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (25, N'Accessories', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (26, N'Shorts', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (27, N'Non Tresca', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (28, N'Cotton', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (29, N'Poly Cot', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (30, N'Tresca', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (31, N'Linen', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (32, N'Apparel', 1, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (33, N'Mens Formal', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (34, N'Shirts', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (35, N'Mens Casual', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (36, N'T shirts', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (37, N'H-Shorts', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (38, N'Jeans', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (39, N'Suiting', 1, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (40, N'Poly Wool', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (41, N'All Wool', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (42, N'Cot Modal', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (43, N'Poly Visc', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (44, N'Silk', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (45, N'Denim', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (46, N'Promo', 1, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (47, N'Accessory', 0, 1)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (48, N'Free GV', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (49, N'Trousers', 0, 0)
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [IsPrimaryCategory], [IsSecondaryCategory]) VALUES (50, N'Socks', 0, 0)
SET IDENTITY_INSERT [dbo].[Categories] OFF
