SET IDENTITY_INSERT [dbo].[TranscationModes] ON
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (1, N'Home Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (2, N'Other Home Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (3, N'Mukesh(Home Staff)')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (4, N'Amit Kumar')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (5, N'Amit Kumar Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (6, N'CashIn')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (7, N'CashOut')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (8, N'Regular')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (9, N'Suspence')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (10, N'OnLinePurchase')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (11, N'Petty Cash Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (12, N'Dan')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (13, N'Breakfast')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (14, N'Lunch')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (15, N'Coffee')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (16, N'Cup Glass')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (17, N'Battery')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (19, N'Fuel Expences')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (20, N'Social & Staff Welfare')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (21, N'Postage & Courier')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (22, N'Snacks & Refreshment')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (23, N'Miscellaneous Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (24, N'Baksheesh & Others')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (25, N'Medicine Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (26, N'Painter')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (27, N'Stationary')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (28, N'Shop Electricity Bill')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (29, N'Mobile bill & Recharge')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (30, N'Labour ')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (31, N'Short in Cash')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (32, N'Repair & Maintenance')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (33, N'Puja Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (34, N'Travelling & Trip Expenses')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (35, N'SINGHANIA SENITRIES')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (36, N'Net Communication')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (38, N'Freight charges')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (39, N'R.S Furniture')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (40, N'Tea')
INSERT INTO [dbo].[TranscationModes] ([TranscationModeId], [Transcation]) VALUES (41, N'Staff Shoes')
SET IDENTITY_INSERT [dbo].[TranscationModes] OFF
