SET IDENTITY_INSERT [dbo].[Salesmen] ON
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (1, N'Manager', NULL, NULL, 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (2, N'Sanjeev Kumar Mishra', 2, N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (3, N'Mukesh Kumar Mandal', 3, N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (4, N'Amit Thakur ', 14, N'AmitKumar', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (5, N'Bikash Kumar Sah', 16, N'Admin', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (6, N'MANAGER', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (7, N'Sourav Turi', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (8, N'Alok', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (9, N'Amit Thakur', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (10, N'AJAM MASTER', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (11, N'Santosh Kumar', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (12, N'Bikas Kumar Sah', NULL, N'AA', 0, 1, 1)
INSERT INTO [dbo].[Salesmen] ([SalesmanId], [SalesmanName], [EmployeeId], [UserId], [EntryStatus], [IsReadOnly], [StoreId]) VALUES (13, N'Jafer master', NULL, N'AA', 0, 1, 1)
SET IDENTITY_INSERT [dbo].[Salesmen] OFF
